name: Auto Build Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'  # Триггерим только при изменении Docker-файлов

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find all Docker projects
        id: find-projects
        run: |
          # Находим все папки с Dockerfile (игнорируем корневой Dockerfile если есть)
          DIRS=$(find . -mindepth 2 -type f -name Dockerfile -exec dirname {} \; | sed 's|^\./||')
          echo "Found Docker projects:"
          echo "$DIRS"
          
          # Формируем JSON для matrix
          MATRIX_JSON=$(jq -n --arg dirs "$DIRS" '
            $dirs | split("\n") | map(select(. != "")) | 
            map({"project_path": .}) | {"include": .}
          ')
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.project_path }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.project_path | replace('/', '-') }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}