name: Docker Image Builder

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**/Dockerfile'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Find all Dockerfiles recursively
        id: find-dockerfiles
        run: |
          # Ищем все Dockerfiles рекурсивно
          DOCKERFILES=$(find . -type f -name Dockerfile)
          FOLDERS=$(dirname $DOCKERFILES)

          # Формируем имена образов
          I=0
          for folder in $FOLDERS; do
            IMAGE_NAME=$(echo "$folder" | sed 's|\./||; s|/|-|g')
            echo "::set-output name=folder_$I::$folder" >> $GITHUB_OUTPUT
            echo "::set-output name=image_name_$I::$IMAGE_NAME" >> $GITHUB_OUTPUT
            ((I++))
          done

      - name: Setup QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker images
        needs: find-dockerfiles
        runs-on: ubuntu-latest
        strategy:
          matrix:
            folders: ${{ range(fromEntries(steps.find-dockerfiles.outputs)) }}
        steps:
          - name: Build specific Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./${{ matrix.folders.value }}/Dockerfile
              platforms: linux/amd64,linux/arm64
              push: true
              tags: |
                ghcr.io/${{ github.repository_owner }}/${{ matrix.folders.key }}:latest
                ghcr.io/${{ github.repository_owner }}/${{ matrix.folders.key }}:${{ github.sha }}