name: Docker Image Builder

on:
  workflow_dispatch:
  push:
    branches:
      - '*'  # Срабатывание на любую ветку
    paths:
      - '**/Dockerfile'  # Запускаем только при изменении Dockerfile'ов

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Find all Dockerfiles recursively
        id: find-dockerfiles
        run: |
          # Рекурсивно находим все Dockerfiles
          DOCKERFILES=$(find . -type f -name Dockerfile)
          FOLDERS=$(dirname $DOCKERFILES)

          # Формируем уникальные имена образов
          I=0
          for folder in $FOLDERS; do
            # Нормализация пути: удаление начальной точки и замена слешей на тире
            IMAGE_NAME=$(echo "$folder" | sed 's|\./||; s|/|-|g')
            echo "::set-output name=folder_$I::$folder" >> $GITHUB_OUTPUT
            echo "::set-output name=image_name_$I::$IMAGE_NAME" >> $GITHUB_OUTPUT
            ((I++))
          done

      - name: Setup QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker images
        strategy:
          matrix:
            folders: ${{ range(fromEntries(steps.find-dockerfiles.outputs)) }}
        run: |
          # Построение конкретного Docker-образа
          docker buildx build \
            --context . \
            --file ${{ matrix.folders.value }}/Dockerfile \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag ghcr.io/${{ github.repository_owner }}/${{ matrix.folders.key }}:latest \
            --tag ghcr.io/${{ github.repository_owner }}/${{ matrix.folders.key }}:${{ github.sha }}