name: Auto Build Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover_and_build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-projects.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find valid Docker projects
        id: find-projects
        run: |
          # Находим все Dockerfile (игнорируя корневой)
          mapfile -t DOCKER_PATHS < <(find . -mindepth 2 -type f -name Dockerfile)
         
         {
           echo "matrix<<EOF"
           jq -n -c --argjson arr "$(printf '%s\n' "${DOCKER_PATHS[@]}" | jq -R -s .)" \
             '$arr | map({
               project_path: (. | sub("^./"; "")),
               image_name: (. | gsub("/"; "-") | gsub("[^a-zA-Z0-9-]"; "-"))
             }) | {include: .}'
           echo "EOF"
         } >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.project_path }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ github.sha }}