name: Build Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'java-graalvm/**/Dockerfile'
      - 'pterodactyl-dockers/**/Dockerfile'

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover_docker_dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find all Docker projects
        id: set-matrix
        run: |
          GRAALVM_DIRS=$(find java-graalvm -type f -name Dockerfile | sed 's|/Dockerfile||' | jq -R -s -c 'split("\n") | map(select(. != ""))')
          GRAALVM_MATRIX=$(echo $GRAALVM_DIRS | jq 'map({"docker_dir": . | sub("java-graalvm/"; ""), "base_dir": "java-graalvm"})')
          PT_DIRS=$(find pterodactyl-dockers -type f -name Dockerfile | sed 's|/Dockerfile||' | jq -R -s -c 'split("\n") | map(select(. != ""))')
          PT_MATRIX=$(echo $PT_DIRS | jq 'map({"docker_dir": . | sub("pterodactyl-dockers/"; ""), "base_dir": "pterodactyl-dockers"})')
          FINAL_MATRIX=$(echo "$GRAALVM_MATRIX $PT_MATRIX" | jq -s 'add')
          echo "matrix={\"include\":$FINAL_MATRIX}" >> $GITHUB_OUTPUT

  build_and_push:
    needs: discover_docker_dirs
    name: "Build ${{ matrix.base_dir }}/${{ matrix.docker_dir }}"
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.discover_docker_dirs.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./${{ matrix.base_dir }}/${{ matrix.docker_dir }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.base_dir }}-${{ matrix.docker_dir }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.base_dir }}-${{ matrix.docker_dir }}:${{ github.sha }}