name: Docker Image Builder

on:
  push:
    branches:
      - '*'  # Активация на любой ветке
    paths:
      - '**/Dockerfile'  # Реакция только на изменения Dockerfile'ов

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Find all Dockerfiles recursively
        id: find-dockerfiles
        run: |
          # Ищем все Dockerfiles рекурсивно (игнорируем корневой)
          mapfile -t DOCKER_PATHS < <(find . -mindepth 2 -type f -name Dockerfile)
          
          # Формируем JSON-матрицу
          MATRIX_JSON=$(jq -n \
            --argjson paths "$(printf '"%s"\n' "${DOCKER_PATHS[@]}" | jq -R -s 'map(select(. != "") | sub("^./"; ""))')" \
            '{
              include: ($paths | map({
                folder: . | dirname,
                image_name: (. | dirname | gsub("/"; "-") | gsub("[^a-zA-Z0-9-]"; "-")
              }))
            }')
          
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
          echo "Found Dockerfiles:"
          echo "$MATRIX_JSON" | jq .

      - name: Setup QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.folder }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ github.sha }}