name: Docker Image Builder

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**/Dockerfile'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Find all Dockerfiles recursively
        id: find-dockerfiles
        run: |
          DOCKERFILES=$(find . -type f -name Dockerfile)
          FOLDERS=$(dirname $DOCKERFILES)
          echo "folders=$FOLDERS" >> $GITHUB_OUTPUT

      - name: Setup QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ steps.find-dockerfiles.outputs.folders }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.find-dockerfiles.outputs.folders | tr '/' '-' }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ steps.find-dockerfiles.outputs.folders | tr '/' '-' }}:${{ github.sha }}