name: Docker Image Builder

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    paths: [ '**/Dockerfile' ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-dockerfiles.outputs.matrix }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Find all Dockerfiles
        id: find-dockerfiles
        run: |
          # Находим все Dockerfile (игнорируя корневой)
          mapfile -t DOCKER_PATHS < <(find . -mindepth 2 -type f -name Dockerfile -print0 | xargs -0 realpath --relative-to=. | grep -v '^$')
          
          if [ ${#DOCKER_PATHS[@]} -eq 0 ]; then
            echo "::error::No Dockerfiles found!"
            exit 1
          fi
          
          JSON_ENTRIES=()
          for path in "${DOCKER_PATHS[@]}"; do
            folder=$(dirname "$path")
            # Приводим всё к нижнему регистру и удаляем недопустимые символы
            image_name=$(echo "$folder" | tr '[:upper:]' '[:lower:]' | tr '/' '-' | sed 's/[^a-z0-9-]//g' | sed 's/^-*//;s/-*$//;s/--*/-/g')
            if [ -z "$image_name" ]; then
              echo "::error::Image name is empty for folder: $folder"
              exit 1
            fi
            JSON_ENTRIES+=("{\"folder\":\"$folder\",\"image_name\":\"$image_name\"}")
          done
          
          MATRIX_JSON="{\"include\":[$(IFS=,; echo "${JSON_ENTRIES[*]}")]}"
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
          echo "Found Dockerfiles:"
          echo "$MATRIX_JSON" | jq .

  build:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build-and-push-images.outputs.matrix) }}
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.folder }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ format('{0}', toLower(github.repository_owner)) }}/${{ matrix.image_name }}:latest
            ghcr.io/${{ format('{0}', toLower(github.repository_owner)) }}/${{ matrix.image_name }}:${{ github.sha }}